# Generated by Django 3.2 on 2022-11-24 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_auto_20221124_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color', to='auto.color', verbose_name='Цвет авто'),
        ),
    ]
