# Generated by Django 3.2 on 2022-11-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
    ]
