# Generated by Django 3.2 on 2022-11-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0010_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default='2022-11-24', verbose_name='Дата заказа'),
        ),
    ]
