# Generated by Django 3.2 on 2022-11-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0011_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default='2022-11-25', verbose_name='Дата заказа'),
        ),
    ]
